/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calJNI */

#ifndef _Included_calJNI
#define _Included_calJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     calJNI
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calJNI_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     calJNI
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calJNI_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     calJNI
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calJNI_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
